[package]
name = "ckb-block-filter"
version = "0.104.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "Create block filter data for client-side filtering"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-store = { path = "../store", version = "= 0.104.0-pre" }
ckb-notify = { path = "../notify", version = "= 0.104.0-pre" }
ckb-channel = { path = "../util/channel", version = "= 0.104.0-pre" }
ckb-logger = { path = "../util/logger", version = "= 0.104.0-pre" }
ckb-types = { path = "../util/types", version = "= 0.104.0-pre" }
golomb-coded-set = { git = "https://github.com/TheWaWaR/golomb-coded-set"}
